#
# Contains environment variable config mapping
#
# See: https://github.com/lorenwest/node-config/wiki/Environment-Variables#custom-environment-variables
#
app_path = "APP_PATH"
password = "PASSWORD"
private_library = "PRIVATE_LIBRARY"
thumbnail_size = "THUMBNAIL_SIZE"
page_title = "PAGE_TITLE"
